version: '3'

services:
  app:
    build: ./
    volumes:
      - ./app:/usr/app
    ports:
      - 4000:4000 # Emulator Suite UI
      - 9099:9099 # Authentication
      - 5001:5001 # Cloud Functions
      - 8080:8080 # Cloud Firestore
      - 9199:9199 # Cloud Storage
    tty: true
    stdin_open: true
    command: /bin/sh